targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - graphql/schema.graphql
    builders:
      artemis:
        options:
          naming_scheme: simple
          generate_helpers: true
          schema_mapping:
            - schema: graphql/schema.graphql
              queries_glob: graphql/**/*.graphql
              output: lib/graphql/graphql_api.dart
          custom_parser_import: "package:bookbook/lib/utils/coercers.dart"
          scalar_mapping:
            - graphql_type: GraphQLDate
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: GraphQLDateTime
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: JSONObject
              dart_type: Map<String, dynamic>